import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import nid_lib from 'nid'
import React, { useState } from 'react';
import bg0 from '../public/images/backgroundImg0.jpg'
import bg1 from '../public/images/backgroundImg1.jpg'
import bg2 from '../public/images/backgroundImg2.jpg'
import bg3 from '../public/images/backgroundImg3.jpg'
import bg4 from '../public/images/backgroundImg4.png'
import bg5 from '../public/images/backgroundImg5.png'


export default function Create() {
  const images = [bg0, bg1, bg2, bg3, bg4, bg5]
  const generate_nid = nid_lib({ length: 8 });
  const [nid, setNID] = useState(generate_nid());
  const [selected, setSelected] = useState(0);
  const [title, setTitle] = useState({
    value: '',
    valid: true
  });
  const [desc, setDesc] = useState({
    value: '',
    valid: true
  });

  function allValid(){
    return title.value.length > 0 && desc.value.length > 0;
  }

  function setValid(){
    setTitle({...title, valid: title.value.length > 0});
    setDesc({...desc, valid: desc.value.length > 0});
  }
  
  return (
    <div className={styles.container} style={{backgroundImage: `url("${images[selected].src}")`, backgroundSize: 'cover'}}>
      <Head>
        <title>Phenom Friendbanking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.createCard}>
          <h1 className='mb-3'>Create your own supporter page</h1>
          <p className='mb-3'>Fill out the form below to personalize the title, description and background image of your supporter page to tell your network why you're supporting the cause.</p>

          <div className='mb-3'>
            <div>Supporter URL</div>
            <div className="input-group">
              <div type="text" className={styles.supporterLink + " form-control"}>{'https://phenomonline.org/friendbanking/' + nid}</div>
              <div className="input-group-append" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
                <button className="btn btn-outline-secondary" type="button" onClick={() => navigator.clipboard.writeText('https://phenomonline.org/friendbanking/' + nid)}>Copy to Clipboard</button>
              </div>             
            </div>
            <small>After you create your page this is the link you will be using to share your support. You'll also be able to see this link on your dashboard.</small>
          </div>

          <div className='mb-3'>
            <label htmlFor='title'>Title</label>
            <input id='title' className='form-control' placeholder="Enter a title for your page" onChange={e => setTitle({...title, value: e.target.value})}></input>
            {title.valid ? null : <small style={{color: 'red'}}>Title cannot be empty</small>}
          </div>

          <div className='mb-3'>
            <label htmlFor='desc'>Share why you're supporting the cause:</label>
            <textarea id='desc' className='form-control' rows='5' onChange={e => setDesc({...desc, value: e.target.value})}></textarea>
            {desc.valid ? null : <small style={{color: 'red'}}>Description cannot be empty</small>}
          </div>

          <div className='mb-1'>
            Choose a background image:
          </div>

          <div className='mx-3 mb-3'>
            <div className='row'>
              <div className={'col ' + ((selected === 0) ? styles.imageSelected : '')} onClick={() => setSelected(0)} style={{height: 100, backgroundImage: `url("${bg0.src}")`, backgroundSize: 'cover'}}>
              </div>
              <div className={'col ' + ((selected === 1) ? styles.imageSelected : '')} onClick={() => setSelected(1)} style={{height: 100, backgroundImage: `url("${bg1.src}")`, backgroundSize: 'cover', marginLeft: 5}}>
              </div>
              <div className={'col ' + ((selected === 2) ? styles.imageSelected : '')} onClick={() => setSelected(2)} style={{height: 100, backgroundImage: `url("${bg2.src}")`, backgroundSize: 'cover', marginLeft: 5}}>
              </div>
              <div className={'col ' + ((selected === 3) ? styles.imageSelected : '')} onClick={() => setSelected(3)} style={{height: 100, backgroundImage: `url("${bg3.src}")`, backgroundSize: 'cover', marginLeft: 5}}>
              </div>
              <div className={'col ' + ((selected === 4) ? styles.imageSelected : '')} onClick={() => setSelected(4)} style={{height: 100, backgroundImage: `url("${bg4.src}")`, backgroundSize: 'cover', marginLeft: 5}}>
              </div>
              <div className={'col ' + ((selected === 5) ? styles.imageSelected : '')} onClick={() => setSelected(5)} style={{height: 100, backgroundImage: `url("${bg5.src}")`, backgroundSize: 'cover', marginLeft: 5}}>
              </div>
            </div>
          </div>
          <button 
            type="button" 
            className={styles.createPageButton + " btn col-2 mt-3"}
            onClick={() => {
              if(allValid()){
                //send data to api route
                setValid();
                alert('valid');
              }
              else {
                setValid();
              }
            }}
          >
            Create Page
          </button>
        </div>
      </main>
    </div>
  )
}