import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Filter from 'bad-words'
import nid_lib from 'nid'
import React, { useState } from 'react';

export default function Create() {
  const filter = new Filter();
  const generate_nid = nid_lib({ length: 8 });
  const [url, setURL] = useState('');
  const [nid, setNID] = useState(generate_nid());
  const [selected, setSelected] = useState(0);

  function validateURL(new_url) {
    if (filter.isProfane(new_url)) {
      alert('BAD!');
      console
    }
    else {
      setURL(new_url);
    }
  }

  function getBackground(){
    switch(selected){
      case 0: return 'red';
      case 1: return 'orange';
      case 2: return 'yellow';
      case 3: return 'green';
      case 4: return 'blue';
    }
  }

  return (
    <div className={styles.container} style={{backgroundColor: getBackground()}}>
      <Head>
        <title>Phenom Friendbanking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.createCard}>
          <h1 className='mb-3'>Create your own supporter page</h1>
          <p className='mb-3'>Fill out the form below to personalize the title, description and background image of your supporter page to tell your network why you're supporting the cause.</p>

          <div className='mb-3'>
            <div>Supporter URL</div>
            <div className="input-group">
              <div type="text" className={styles.supporterLink + " form-control"}>{'https://phenomonline.org/friendbanking/' + nid}</div>
              <div className="input-group-append" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
                <button className="btn btn-outline-secondary" type="button" onClick={() => navigator.clipboard.writeText('https://phenomonline.org/friendbanking/' + nid)}>Copy to Clipboard</button>
              </div>             
            </div>
            <small>After you create your page this is the link you will be using to share your support. You'll also be able to see this link on your dashboard.</small>
          </div>

          <div className='mb-3'>
            <label htmlFor='title'>Title</label>
            <input id='title' className='form-control' placeholder="Enter a title for your page"></input>
          </div>

          <div className='mb-3'>
            <label htmlFor='desc'>Share why you're supporting the cause:</label>
            <textarea id='desc' className='form-control' rows='5'></textarea>
          </div>

          <div className='mx-3 mb-3'>
            <div className='row'>
              <div className={'col ' + ((selected === 0) ? styles.imageSelected : '')} onClick={() => setSelected(0)} style={{height: 50, backgroundColor: 'red'}}>
                Image0
              </div>
              <div className={'col offset-md-1 ' + ((selected === 1) ? styles.imageSelected : '')} onClick={() => setSelected(1)} style={{height: 50, backgroundColor: 'orange'}}>
              Image1
              </div>
              <div className={'col offset-md-1 ' + ((selected === 2) ? styles.imageSelected : '')} onClick={() => setSelected(2)} style={{height: 50, backgroundColor: 'yellow'}}>
              Image2
              </div>
              <div className={'col offset-md-1 ' + ((selected === 3) ? styles.imageSelected : '')} onClick={() => setSelected(3)} style={{height: 50, backgroundColor: 'blue'}}>
              Image3
              </div>
              <div className={'col offset-md-1 ' + ((selected === 4) ? styles.imageSelected : '')} onClick={() => setSelected(4)} style={{height: 50, backgroundColor: 'green'}}>
              Image4
              </div>
            </div>
          </div>
          <button type="button" className={styles.createPageButton + " btn col-2 mt-3"}>Create Page</button>
        </div>
      </main>
    </div>
  )
}