import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';

export default function Create() {
  return (
    //Make background based on what picture is in db
    <div className={styles.container}>
      <Head>
        <title>Phenom Friendbanking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.createCard}>
          <h1 className='mb-3'>Become a supporter! (this title will be in the database)</h1>
          <p className='mb-3'>Fill out the information below to show your support for X (this description will be in the database)</p>

          <div className='mb-3'>
            <label htmlFor='title'>Full name</label>
            <input id='name' className='form-control' placeholder="Enter your full name"></input>
          </div>

          <div className='mb-3'>
            <label htmlFor='title'>Email</label>
            <input id='email' className='form-control' placeholder="Enter your email"></input>
          </div>

          <div className='mb-3'>
            <label htmlFor='title'>Voting Address</label>
            <input id='address' className='form-control' placeholder="Enter your address"></input>
            <small>This is only used to determine congressional districts</small>
          </div>

          <div className='mb-3'>
            <label htmlFor='title'>Phone number</label>
            <input id='phone' className='form-control' placeholder="Enter your phone number"></input>
            <small>Not sure what this will be used for, is it necessary?</small>
          </div>

          <div className='mb-3'>
            <label htmlFor='title'>Why do you want to support this cause?</label>
            <textarea id='whysupport' className='form-control' rows='5'></textarea>
          </div>
          <button type="button" className={styles.createPageButton + " btn col-3 mt-3"}>Join the cause</button>
        </div>
      </main>
    </div>
  )
}